
// Objective-C API for talking to the following Go packages
//
//	github.com/mycreditchain/mcc
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mcc_FRAMEWORK_H__
#define __Mcc_FRAMEWORK_H__

#include "Mcc.objc.h"
#include "universe.objc.h"

#endif
