// Objective-C API for talking to github.com/mycreditchain/mcc Go package.
//   gobind -lang=objc github.com/mycreditchain/mcc
//
// File is generated by gobind. Do not edit.

#ifndef __Mcc_H__
#define __Mcc_H__

@import Foundation;
#include "Universe.objc.h"


@class MccSignData;
@class MccWallet;

@interface MccSignData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)r;
- (void)setR:(NSString*)v;
- (NSString*)s;
- (void)setS:(NSString*)v;
@end

@interface MccWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)privatekey;
- (void)setPrivatekey:(NSString*)v;
- (NSString*)publickey;
- (void)setPublickey:(NSString*)v;
@end

FOUNDATION_EXPORT NSString* MccDecrypt(NSString* privateKey, NSString* cryptString, NSError** error);

FOUNDATION_EXPORT NSString* MccEncrypt(NSString* publickey, NSString* message, NSError** error);

/**
 * NewGreeter makes a new Greeter.
 */
FOUNDATION_EXPORT MccWallet* MccGenerateWallet(NSError** error);

/**
 * NewGreeter makes a new Greeter.
 */
FOUNDATION_EXPORT MccSignData* MccSign(NSString* privateKey, NSString* hash, NSError** error);

FOUNDATION_EXPORT BOOL MccVerify(NSString* publickey, NSString* hash, NSString* r, NSString* s);

#endif
